package RequirementEngineering.editor;

/*Generated by MPS */

import jetbrains.mps.openapi.editor.descriptor.EditorAspectDescriptor;
import java.util.Collection;
import jetbrains.mps.openapi.editor.descriptor.ConceptEditor;
import jetbrains.mps.smodel.runtime.ConceptDescriptor;
import java.util.Arrays;
import java.util.Collections;
import jetbrains.mps.openapi.editor.descriptor.ConceptEditorComponent;

public class EditorAspectDescriptorImpl implements EditorAspectDescriptor {

  public Collection<ConceptEditor> getEditors(ConceptDescriptor descriptor) {
    switch (Arrays.binarySearch(stringSwitchCases_xbvbvu_a0a0b, descriptor.getConceptFqName())) {
      case 0:
        return Collections.<ConceptEditor>singletonList(new Data_Editor());
      case 1:
        return Collections.<ConceptEditor>singletonList(new Feature_Editor());
      case 2:
        return Collections.<ConceptEditor>singletonList(new Given_Editor());
      case 3:
        return Collections.<ConceptEditor>singletonList(new Goal_Editor());
      case 4:
        return Collections.<ConceptEditor>singletonList(new Interaction_Editor());
      case 5:
        return Collections.<ConceptEditor>singletonList(new Loading_Editor());
      case 6:
        return Collections.<ConceptEditor>singletonList(new Project_Editor());
      case 7:
        return Collections.<ConceptEditor>singletonList(new Scenario_Editor());
      case 8:
        return Collections.<ConceptEditor>singletonList(new Update_Editor());
      case 9:
        return Collections.<ConceptEditor>singletonList(new View_Editor());
      default:
    }
    return Collections.<ConceptEditor>emptyList();
  }
  public Collection<ConceptEditorComponent> getEditorComponents(ConceptDescriptor descriptor, String editorComponentId) {
    return Collections.<ConceptEditorComponent>emptyList();
  }


  private static String[] stringSwitchCases_xbvbvu_a0a0b = new String[]{"RequirementEngineering.structure.Data", "RequirementEngineering.structure.Feature", "RequirementEngineering.structure.Given", "RequirementEngineering.structure.Goal", "RequirementEngineering.structure.Interaction", "RequirementEngineering.structure.Loading", "RequirementEngineering.structure.Project", "RequirementEngineering.structure.Scenario", "RequirementEngineering.structure.Update", "RequirementEngineering.structure.View"};
}
