package RequirementEngineering.structure;

/*Generated by MPS */

import java.util.List;
import jetbrains.mps.internal.collections.runtime.ListSequence;
import java.util.LinkedList;

public enum EAction {
  next("next", "next"),
  previous("previous", "previous"),
  range_selected("range", "range selected"),
  element_clicked("element", "element clicked");

  private String myName;
  public String getName() {
    return this.myName;
  }
  public String getValueAsString() {
    return this.myValue;
  }
  public static List<EAction> getConstants() {
    List<EAction> list = ListSequence.fromList(new LinkedList<EAction>());
    ListSequence.fromList(list).addElement(EAction.next);
    ListSequence.fromList(list).addElement(EAction.previous);
    ListSequence.fromList(list).addElement(EAction.range_selected);
    ListSequence.fromList(list).addElement(EAction.element_clicked);
    return list;
  }
  public static EAction getDefault() {
    return null;
  }
  public static EAction parseValue(String value) {
    if (value == null) {
      return EAction.getDefault();
    }
    if (value.equals(EAction.next.getValueAsString())) {
      return EAction.next;
    }
    if (value.equals(EAction.previous.getValueAsString())) {
      return EAction.previous;
    }
    if (value.equals(EAction.range_selected.getValueAsString())) {
      return EAction.range_selected;
    }
    if (value.equals(EAction.element_clicked.getValueAsString())) {
      return EAction.element_clicked;
    }
    return EAction.getDefault();
  }
  private String myValue;
  EAction(String name, String value) {
    this.myName = name;
    this.myValue = value;
  }
  public String getValue() {
    return this.myValue;
  }
}
