package RequirementEngineering.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.BaseStructureAspectDescriptor;
import jetbrains.mps.smodel.runtime.ConceptDescriptor;
import jetbrains.mps.smodel.runtime.impl.ConceptDescriptorBuilder;
import jetbrains.mps.smodel.adapter.ids.MetaIdFactory;
import java.util.Collection;
import java.util.Arrays;
import org.jetbrains.annotations.Nullable;

public class StructureAspectDescriptor extends BaseStructureAspectDescriptor {

  /*package*/ final ConceptDescriptor myConceptData = new ConceptDescriptorBuilder("RequirementEngineering.structure.Data", MetaIdFactory.conceptId(0x29964a4c1fd5485aL, 0x8f37bb744b44ca74L, 0x1cc9d34e19cec8dcL)).super_("jetbrains.mps.lang.core.structure.BaseConcept").super_(MetaIdFactory.conceptId(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x10802efe25aL)).parents("jetbrains.mps.lang.core.structure.BaseConcept", "jetbrains.mps.lang.core.structure.INamedConcept").parentIds(MetaIdFactory.conceptId(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x10802efe25aL), MetaIdFactory.conceptId(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L)).create();
  /*package*/ final ConceptDescriptor myConceptFeature = new ConceptDescriptorBuilder("RequirementEngineering.structure.Feature", MetaIdFactory.conceptId(0x29964a4c1fd5485aL, 0x8f37bb744b44ca74L, 0x1cc9d34e19ceb9edL)).super_("jetbrains.mps.lang.core.structure.BaseConcept").super_(MetaIdFactory.conceptId(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x10802efe25aL)).parents("jetbrains.mps.lang.core.structure.BaseConcept", "jetbrains.mps.lang.core.structure.INamedConcept").parentIds(MetaIdFactory.conceptId(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x10802efe25aL), MetaIdFactory.conceptId(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L)).propertyDescriptors(new ConceptDescriptorBuilder.Prop(2074421435774712308L, "description")).properties("description").childDescriptors(new ConceptDescriptorBuilder.Link(2074421435774712319L, "scenarii", MetaIdFactory.conceptId(0x29964a4c1fd5485aL, 0x8f37bb744b44ca74L, 0x1cc9d34e19ceb9feL), false, true, false)).children(new String[]{"scenarii"}, new boolean[]{true}).create();
  /*package*/ final ConceptDescriptor myConceptGiven = new ConceptDescriptorBuilder("RequirementEngineering.structure.Given", MetaIdFactory.conceptId(0x29964a4c1fd5485aL, 0x8f37bb744b44ca74L, 0x1cc9d34e19ceba0cL)).super_("jetbrains.mps.lang.core.structure.BaseConcept").super_(MetaIdFactory.conceptId(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x10802efe25aL)).parents("jetbrains.mps.lang.core.structure.BaseConcept").parentIds(MetaIdFactory.conceptId(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x10802efe25aL)).propertyDescriptors(new ConceptDescriptorBuilder.Prop(2074421435774712333L, "dashboard")).properties("dashboard").create();
  /*package*/ final ConceptDescriptor myConceptGoal = new ConceptDescriptorBuilder("RequirementEngineering.structure.Goal", MetaIdFactory.conceptId(0x29964a4c1fd5485aL, 0x8f37bb744b44ca74L, 0x1cc9d34e19cec887L)).super_("RequirementEngineering.structure.Then").super_(MetaIdFactory.conceptId(0x29964a4c1fd5485aL, 0x8f37bb744b44ca74L, 0x1cc9d34e19ceba10L)).parents("RequirementEngineering.structure.Then").parentIds(MetaIdFactory.conceptId(0x29964a4c1fd5485aL, 0x8f37bb744b44ca74L, 0x1cc9d34e19ceba10L)).propertyDescriptors(new ConceptDescriptorBuilder.Prop(2074421435774716042L, "function")).properties("function").childDescriptors(new ConceptDescriptorBuilder.Link(2074421435774716128L, "data", MetaIdFactory.conceptId(0x29964a4c1fd5485aL, 0x8f37bb744b44ca74L, 0x1cc9d34e19cec8dcL), true, true, false)).children(new String[]{"data"}, new boolean[]{true}).alias("then goal", "").create();
  /*package*/ final ConceptDescriptor myConceptInteraction = new ConceptDescriptorBuilder("RequirementEngineering.structure.Interaction", MetaIdFactory.conceptId(0x29964a4c1fd5485aL, 0x8f37bb744b44ca74L, 0x1cc9d34e19cf16fbL)).super_("RequirementEngineering.structure.When").super_(MetaIdFactory.conceptId(0x29964a4c1fd5485aL, 0x8f37bb744b44ca74L, 0x1cc9d34e19ceba0fL)).parents("RequirementEngineering.structure.When").parentIds(MetaIdFactory.conceptId(0x29964a4c1fd5485aL, 0x8f37bb744b44ca74L, 0x1cc9d34e19ceba0fL)).propertyDescriptors(new ConceptDescriptorBuilder.Prop(2074421435774736124L, "action"), new ConceptDescriptorBuilder.Prop(2074421435775044051L, "elementID")).properties("action", "elementID").alias("when interaction", "").create();
  /*package*/ final ConceptDescriptor myConceptLoading = new ConceptDescriptorBuilder("RequirementEngineering.structure.Loading", MetaIdFactory.conceptId(0x29964a4c1fd5485aL, 0x8f37bb744b44ca74L, 0x1cc9d34e19cf16f8L)).super_("RequirementEngineering.structure.When").super_(MetaIdFactory.conceptId(0x29964a4c1fd5485aL, 0x8f37bb744b44ca74L, 0x1cc9d34e19ceba0fL)).parents("RequirementEngineering.structure.When").parentIds(MetaIdFactory.conceptId(0x29964a4c1fd5485aL, 0x8f37bb744b44ca74L, 0x1cc9d34e19ceba0fL)).propertyDescriptors(new ConceptDescriptorBuilder.Prop(2074421435774736121L, "newState")).properties("newState").alias("when edited state", "").create();
  /*package*/ final ConceptDescriptor myConceptProject = new ConceptDescriptorBuilder("RequirementEngineering.structure.Project", MetaIdFactory.conceptId(0x29964a4c1fd5485aL, 0x8f37bb744b44ca74L, 0x1cc9d34e19ceb9eaL)).super_("jetbrains.mps.lang.core.structure.BaseConcept").super_(MetaIdFactory.conceptId(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x10802efe25aL)).parents("jetbrains.mps.lang.core.structure.BaseConcept", "jetbrains.mps.lang.core.structure.INamedConcept").parentIds(MetaIdFactory.conceptId(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x10802efe25aL), MetaIdFactory.conceptId(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L)).childDescriptors(new ConceptDescriptorBuilder.Link(2074421435774712304L, "consistof", MetaIdFactory.conceptId(0x29964a4c1fd5485aL, 0x8f37bb744b44ca74L, 0x1cc9d34e19ceb9edL), false, true, false), new ConceptDescriptorBuilder.Link(2074421435774712324L, "views", MetaIdFactory.conceptId(0x29964a4c1fd5485aL, 0x8f37bb744b44ca74L, 0x1cc9d34e19ceba1aL), true, true, false)).children(new String[]{"consistof", "views"}, new boolean[]{true, true}).create();
  /*package*/ final ConceptDescriptor myConceptScenario = new ConceptDescriptorBuilder("RequirementEngineering.structure.Scenario", MetaIdFactory.conceptId(0x29964a4c1fd5485aL, 0x8f37bb744b44ca74L, 0x1cc9d34e19ceb9feL)).super_("jetbrains.mps.lang.core.structure.BaseConcept").super_(MetaIdFactory.conceptId(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x10802efe25aL)).parents("jetbrains.mps.lang.core.structure.BaseConcept", "jetbrains.mps.lang.core.structure.INamedConcept").parentIds(MetaIdFactory.conceptId(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x10802efe25aL), MetaIdFactory.conceptId(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L)).childDescriptors(new ConceptDescriptorBuilder.Link(2074421435774712337L, "givens", MetaIdFactory.conceptId(0x29964a4c1fd5485aL, 0x8f37bb744b44ca74L, 0x1cc9d34e19ceba0cL), false, true, false), new ConceptDescriptorBuilder.Link(2074421435774712339L, "whens", MetaIdFactory.conceptId(0x29964a4c1fd5485aL, 0x8f37bb744b44ca74L, 0x1cc9d34e19ceba0fL), false, true, false), new ConceptDescriptorBuilder.Link(2074421435774712342L, "thens", MetaIdFactory.conceptId(0x29964a4c1fd5485aL, 0x8f37bb744b44ca74L, 0x1cc9d34e19ceba10L), false, true, false)).children(new String[]{"givens", "whens", "thens"}, new boolean[]{true, true, true}).create();
  /*package*/ final ConceptDescriptor myConceptThen = new ConceptDescriptorBuilder("RequirementEngineering.structure.Then", MetaIdFactory.conceptId(0x29964a4c1fd5485aL, 0x8f37bb744b44ca74L, 0x1cc9d34e19ceba10L)).super_("jetbrains.mps.lang.core.structure.BaseConcept").super_(MetaIdFactory.conceptId(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x10802efe25aL)).parents("jetbrains.mps.lang.core.structure.BaseConcept").parentIds(MetaIdFactory.conceptId(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x10802efe25aL)).abstract_().create();
  /*package*/ final ConceptDescriptor myConceptUpdate = new ConceptDescriptorBuilder("RequirementEngineering.structure.Update", MetaIdFactory.conceptId(0x29964a4c1fd5485aL, 0x8f37bb744b44ca74L, 0x1cc9d34e19cec8e4L)).super_("RequirementEngineering.structure.Then").super_(MetaIdFactory.conceptId(0x29964a4c1fd5485aL, 0x8f37bb744b44ca74L, 0x1cc9d34e19ceba10L)).parents("RequirementEngineering.structure.Then").parentIds(MetaIdFactory.conceptId(0x29964a4c1fd5485aL, 0x8f37bb744b44ca74L, 0x1cc9d34e19ceba10L)).propertyDescriptors(new ConceptDescriptorBuilder.Prop(2074421435775078219L, "reaction")).properties("reaction").referenceDescriptors(new ConceptDescriptorBuilder.Ref(2074421435774716135L, "target", MetaIdFactory.conceptId(0x29964a4c1fd5485aL, 0x8f37bb744b44ca74L, 0x1cc9d34e19ceba1aL), false)).references("target").alias("then view update", "").create();
  /*package*/ final ConceptDescriptor myConceptView = new ConceptDescriptorBuilder("RequirementEngineering.structure.View", MetaIdFactory.conceptId(0x29964a4c1fd5485aL, 0x8f37bb744b44ca74L, 0x1cc9d34e19ceba1aL)).super_("jetbrains.mps.lang.core.structure.BaseConcept").super_(MetaIdFactory.conceptId(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x10802efe25aL)).parents("jetbrains.mps.lang.core.structure.BaseConcept", "jetbrains.mps.lang.core.structure.INamedConcept").parentIds(MetaIdFactory.conceptId(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x10802efe25aL), MetaIdFactory.conceptId(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L)).propertyDescriptors(new ConceptDescriptorBuilder.Prop(2074421435774712349L, "purpose")).properties("purpose").create();
  /*package*/ final ConceptDescriptor myConceptWhen = new ConceptDescriptorBuilder("RequirementEngineering.structure.When", MetaIdFactory.conceptId(0x29964a4c1fd5485aL, 0x8f37bb744b44ca74L, 0x1cc9d34e19ceba0fL)).super_("jetbrains.mps.lang.core.structure.BaseConcept").super_(MetaIdFactory.conceptId(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x10802efe25aL)).parents("jetbrains.mps.lang.core.structure.BaseConcept").parentIds(MetaIdFactory.conceptId(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x10802efe25aL)).referenceDescriptors(new ConceptDescriptorBuilder.Ref(2074421435774786693L, "view", MetaIdFactory.conceptId(0x29964a4c1fd5485aL, 0x8f37bb744b44ca74L, 0x1cc9d34e19ceba1aL), false)).references("view").abstract_().create();

  @Override
  public Collection<ConceptDescriptor> getDescriptors() {
    return Arrays.asList(myConceptData, myConceptFeature, myConceptGiven, myConceptGoal, myConceptInteraction, myConceptLoading, myConceptProject, myConceptScenario, myConceptThen, myConceptUpdate, myConceptView, myConceptWhen);
  }

  @Override
  @Nullable
  public ConceptDescriptor getDescriptor(String conceptFqName) {
    switch (Arrays.binarySearch(stringSwitchCases_1htk8d_a0a0q, conceptFqName)) {
      case 0:
        return myConceptData;
      case 1:
        return myConceptFeature;
      case 2:
        return myConceptGiven;
      case 3:
        return myConceptGoal;
      case 4:
        return myConceptInteraction;
      case 5:
        return myConceptLoading;
      case 6:
        return myConceptProject;
      case 7:
        return myConceptScenario;
      case 8:
        return myConceptThen;
      case 9:
        return myConceptUpdate;
      case 10:
        return myConceptView;
      case 11:
        return myConceptWhen;
      default:
        return null;
    }
  }
  private static String[] stringSwitchCases_1htk8d_a0a0q = new String[]{"RequirementEngineering.structure.Data", "RequirementEngineering.structure.Feature", "RequirementEngineering.structure.Given", "RequirementEngineering.structure.Goal", "RequirementEngineering.structure.Interaction", "RequirementEngineering.structure.Loading", "RequirementEngineering.structure.Project", "RequirementEngineering.structure.Scenario", "RequirementEngineering.structure.Then", "RequirementEngineering.structure.Update", "RequirementEngineering.structure.View", "RequirementEngineering.structure.When"};
}
