package RequirementEngineering.behavior;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.BehaviorDescriptor;
import java.util.Arrays;
import jetbrains.mps.smodel.runtime.interpreted.BehaviorAspectInterpreted;

public class BehaviorAspectDescriptor implements jetbrains.mps.smodel.runtime.BehaviorAspectDescriptor {
  public BehaviorAspectDescriptor() {
  }
  public BehaviorDescriptor getDescriptor(String fqName) {
    switch (Arrays.binarySearch(stringSwitchCases_846f5o_a0a0b, fqName)) {
      case 6:
        return new Project_BehaviorDescriptor();
      case 1:
        return new Feature_BehaviorDescriptor();
      case 8:
        return new Scenario_BehaviorDescriptor();
      case 2:
        return new Given_BehaviorDescriptor();
      case 9:
        return new View_BehaviorDescriptor();
      case 3:
        return new Goal_BehaviorDescriptor();
      case 0:
        return new Data_BehaviorDescriptor();
      case 7:
        return new Reachability_BehaviorDescriptor();
      case 5:
        return new Loading_BehaviorDescriptor();
      case 4:
        return new Interaction_BehaviorDescriptor();
      default:
        return BehaviorAspectInterpreted.getInstance().getDescriptor(fqName);
    }
  }
  private static String[] stringSwitchCases_846f5o_a0a0b = new String[]{"RequirementEngineering.structure.Data", "RequirementEngineering.structure.Feature", "RequirementEngineering.structure.Given", "RequirementEngineering.structure.Goal", "RequirementEngineering.structure.Interaction", "RequirementEngineering.structure.Loading", "RequirementEngineering.structure.Project", "RequirementEngineering.structure.Reachability", "RequirementEngineering.structure.Scenario", "RequirementEngineering.structure.View"};
}
