package RequirementEngineering.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.BaseConcept_BehaviorDescriptor;

public class Given_BehaviorDescriptor extends BaseConcept_BehaviorDescriptor {
  public Given_BehaviorDescriptor() {
  }
  @Override
  public String getConceptFqName() {
    return "RequirementEngineering.structure.Given";
  }
}
