package RequirementEngineering.behavior;

/*Generated by MPS */


public class Goal_BehaviorDescriptor extends Then_BehaviorDescriptor {
  public Goal_BehaviorDescriptor() {
  }
  @Override
  public String getConceptFqName() {
    return "RequirementEngineering.structure.Goal";
  }
}
