package RequirementEngineering.behavior;

/*Generated by MPS */


public class Interaction_BehaviorDescriptor extends When_BehaviorDescriptor {
  public Interaction_BehaviorDescriptor() {
  }
  @Override
  public String getConceptFqName() {
    return "RequirementEngineering.structure.Interaction";
  }
}
