package RequirementEngineering.behavior;

/*Generated by MPS */


public class Loading_BehaviorDescriptor extends When_BehaviorDescriptor {
  public Loading_BehaviorDescriptor() {
  }
  @Override
  public String getConceptFqName() {
    return "RequirementEngineering.structure.Loading";
  }
}
