package RequirementEngineering.behavior;

/*Generated by MPS */


public class Reachability_BehaviorDescriptor extends Then_BehaviorDescriptor {
  public Reachability_BehaviorDescriptor() {
  }
  @Override
  public String getConceptFqName() {
    return "RequirementEngineering.structure.Reachability";
  }
}
