package RequirementEngineering.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.BaseConcept_BehaviorDescriptor;

public abstract class Then_BehaviorDescriptor extends BaseConcept_BehaviorDescriptor {
  public Then_BehaviorDescriptor() {
  }
  @Override
  public String getConceptFqName() {
    return "RequirementEngineering.structure.Then";
  }
}
