package RequirementEngineering.behavior;

/*Generated by MPS */


public class Update_BehaviorDescriptor extends Then_BehaviorDescriptor {
  public Update_BehaviorDescriptor() {
  }
  @Override
  public String getConceptFqName() {
    return "RequirementEngineering.structure.Update";
  }
}
