package RequirementEngineering.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.BaseConcept_BehaviorDescriptor;

public abstract class When_BehaviorDescriptor extends BaseConcept_BehaviorDescriptor {
  public When_BehaviorDescriptor() {
  }
  @Override
  public String getConceptFqName() {
    return "RequirementEngineering.structure.When";
  }
}
